server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
    name: fengyang_DS
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    driver-class-name: com.mysql.jdbc.Driver
    #基本属性
    url: jdbc:mysql://localhost:3306/cloudDB02?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: rootchu
    password: Yangsha130333
  main:
      allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
ly:
  jwt:
    pubKeyPath: /home/yang/disk30/fengyang/rsa/id_rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  worker:
    workerId: 1
    dataCenterId: 1
  pay:
      appId: wx8397f8696b538317
      mchId: 1473426802
      key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
      httpconnectTimeoutMs: 5000
      httpreadTimeoutMs: 10000
      notifyUrl: http://h7rmfa.natappfree.cc/wxpay/notify  # 内网穿透  微信会将用户的支付结果通过此链接响应给商户